### ISSUE TITLE
валідаційна схема

### ISSUE THREAD

**Issue by pecourses** [DenisPitsul/react-formik#1]
https://github.com/DenisPitsul/react-formik/blob/ae261fb93402c6b48ee2bb62557b627c658f72ea/src/utils/schemas.js#L51
- щоб зареєструватися могла тільки та особа, яка погодилась з правилами, можна додатково виставити, що в цьому полі має бути `true`:
```javascript
 agreement: yup.boolean().oneOf([true]).required("You must accept the agreement"), 
```

**Comment by DenisPitsul** [comment]
Fixed in commit:
https://github.com/DenisPitsul/react-formik/commit/c152922f792eaccc89a0d05b10e43189433e4f85
