### ISSUE TITLE
назва поля

### ISSUE THREAD

**Issue by pecourses** [DenisPitsul/react-formik#2]
https://github.com/DenisPitsul/react-formik/blob/ae261fb93402c6b48ee2bb62557b627c658f72ea/src/components/SignUpForm/index.jsx#L15
- скоріше, щось типу `role`:
```javascript
 role: "buyer", 
```

**Comment by DenisPitsul** [comment]
Fixed in commit:
https://github.com/DenisPitsul/react-formik/commit/c152922f792eaccc89a0d05b10e43189433e4f85
